### ISSUE TITLE
npm out of date

### ISSUE THREAD

**Issue by GabrielDelepine** [pablodenadai/angular2-inline-template-style#11]
Hi,

I see the newest commit out of the last npm release. I don't know what process is involve.

https://www.npmjs.com/package/angular2-inline-template-style

Thanks

**Comment by pablodenadai** [comment]
Done - deployed under version `0.2.1`.

**Comment by GabrielDelepine** [comment]
Thanks @ghpabs and sorry about opening this issue. I didn't see your last message [here](https://github.com/ghpabs/angular2-inline-template-style/pull/9#issuecomment-247040820).

**Comment by pablodenadai** [comment]
No problem
