### ISSUE TITLE
Using single quote can lead to typescript compilation error

### ISSUE THREAD

**Issue by maxailloud** [pablodenadai/angular2-inline-template-style#12]
Hi there,

Thank you for your plugin, I'm using it though the grunt plugin and it's working great.
I just ran into an edge case where using single quote to surround the inlined style is not a goo idea.
I'm using `content`css code and with single quote and I've got a typescript compilation error because of that.

Do you think having an option to choose either you want single-quoted inlined code or not could be good to add or not?

Just asking before doing the PR.

**Comment by pablodenadai** [comment]
Fixed in https://github.com/pablodenadai/angular2-inline-template-style/pull/14
