### ISSUE TITLE
Line breaks in source template currently not considered

### ISSUE THREAD

**Issue by BenjaminBrandmeier** [pablodenadai/angular2-inline-template-style#15]
Hey man, thanks for that library. It really helps out over here!

One thing I noticed. I have the following component:
```
<img #imageElement
     *ngFor='let img of imgrow; let j = index' />
```
which gets translated to:

`<img #imageElement*ngFor=\'let img of imgrow; let j = index\'/>`

The resulting template can't be interpreted that way because #imageElement and *ngFor are stuck together. It would be great if linebreaks will either be copied over to the target template or replaced by a whitespace.

Thanks!

**Comment by pablodenadai** [comment]
Should be fairly simple if you'd like to try a PR.

Something along the lines: 

`.replace(/\n/g, ' ');`

I'm a bit busy atm but I can look into it later on.

**Comment by BenjaminBrandmeier** [comment]
Sounds good. I'm also pretty busy atm, but will try to make a PR within the next days.

**Comment by BenjaminBrandmeier** [comment]
I just realized that using the compress option (-c) eliminates this problem, since html-min and clean-css are applied before inlining, which do take care about line breaks.

For that I will close this issue.
