### ISSUE TITLE
No out path - just write back to javascript file

### ISSUE THREAD

**Issue by real-marco-b** [pablodenadai/angular2-inline-template-style#20]
Any chance ng2-inline supports overwriting the source js file instead of requiring some out path?
The cli works nice but this would really be an essential option. Am I missing some configuration?

Thank you in advance.

**Comment by real-marco-b** [comment]
As I did not find any possibility, I implemented the feature on a fork. I'll make a pull request. :)

**Comment by vlio20** [comment]
+1
