### ISSUE TITLE
Only processes the first js file encountered and then quits with no error.

### ISSUE THREAD

**Issue by jasonburrows** [pablodenadai/angular2-inline-template-style#22]
I run this with `ng2-inline -o build/inlined -b build build/**/*.js` - it just processes the very first js file it encounters and then stops with no errors.  It "correctly" processes that file (in that it outputs it, but since it has nothing to inline, it outputs it unmodified), but never continues on to other files.

**Comment by RomanHotsiy** [comment]
@jasonburrows wrap glob pattern in quotes:

`ng2-inline -o build/inlined -b build "build/**/*.js"`

It is probably related to your shell expanding stars.

**Comment by jasonburrows** [comment]
I have since moved on to a different build process so I can't test your recommendation at this point.  That's for the advice though - it makes sense.
