### ISSUE TITLE
Documentation doesnt explain -r for CLI

### ISSUE THREAD

**Issue by prosanes** [pablodenadai/angular2-inline-template-style#7]
It would be nice for the documentation to explain that -r keeps the relative paths. I had to look into the code to learn that.

Not using it, I'd receive the following error:

> fs.js:634
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open 'app.component.css'
>     at Error (native)

**Comment by gund** [comment]
+1 for the documentation of this argument.

Thanks to this issue cli started to work =)
